# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - 1.1
  - nightly
matrix:
  allow_failures:
    - julia: nightly, 0.7
    - os: osx
notifications:
  email: false
sudo: required
script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.test("PoincareInvariants", coverage=true)'
after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'Pkg.add("Coverage")'
  - julia -e 'cd(Pkg.dir("PoincareInvariants")); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("PoincareInvariants")); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'cd(Pkg.dir("PoincareInvariants")); using Coverage; Coveralls.submit(process_folder())'
