language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.3
  - 1.4
  - nightly

env:
  - PYTHON=""

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true

notifications:
  email: false

codecov: true
coveralls: true
