language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
    - os: osx
notifications:
  email: false
codecov: true
coveralls: true
after_script:
  - bash ./docs/travis.sh
