name = "PoincareInvariants"
uuid = "26663084-47d3-540f-bd97-40ca743aafa4"
authors = ["Michael Kraus <michael.kraus@ipp.mpg.de>"]
version = "0.1.1"

[deps]
ApproxFun = "28f2ccd6-bb30-5033-b560-165f7b14dc2f"
GeometricIntegrators = "dcce2d33-59f6-5b8d-9047-0defad88ae06"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"

[compat]
ApproxFun = "0.10, 0.11"
GeometricIntegrators = "0.2"
HDF5 = "0.10, 0.12"
ProgressMeter = "^1.0"
SafeTestsets = "^0.0.1"
SymPy = "1.0"
julia = "^1.1"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets"]
